### ISSUE TITLE
Support matrix include from travis.yml

### ISSUE THREAD

**Issue by denzelem** [makandra/gemika#3]
Travis CI seems to support an [include](https://docs.travis-ci.com/user/build-matrix/) option for the test matrix.

```
matrix:
  include:
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
  - rvm: 2.5
    gemfile: gemfiles/Gemfile.rails-3.2.x
```

I would prefer a matrix that uses `include` over `exclude` as it is easier to read.

Here is an example where I was confused about which version is used for which Rails version:

```
rvm:
  - '2.2.4'
  - '2.3.1'
  - '2.4.1'
  - '2.5.3'

gemfile:
  - 'Gemfile.3.2.mysql2'
  - 'Gemfile.4.2.mysql2'
  - 'Gemfile.4.2.pg'
  - 'Gemfile.5.2.mysql2'
  - 'Gemfile.5.2.pg'
  - 'Gemfile.6.0.pg'

matrix:
  exclude:
    # Rails 3.2
    - gemfile: 'Gemfile.3.2.mysql2'
      rvm: '2.3.1'
    - gemfile: 'Gemfile.3.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.3.2.mysql2'
      rvm: '2.5.3'
    # Rails 4.2
    - gemfile: 'Gemfile.4.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.4.2.pg'
      rvm: '2.4.1'
    - gemfile: 'Gemfile.4.2.mysql2'
      rvm: '2.5.3'
    - gemfile: 'Gemfile.4.2.pg'
      rvm: '2.5.3'
    # Rails 5.2
    # Rails 6
    - gemfile: 'Gemfile.6.0.pg'
      rvm: '2.2.4'
    - gemfile: 'Gemfile.6.0.pg'
      rvm: '2.3.1'
    - gemfile: 'Gemfile.6.0.pg'
      rvm: '2.4.1'
```

@triskweline What do you think?
