### ISSUE TITLE
Improve support for rbenv aliases

### ISSUE THREAD

**Issue by makmic** [makandra/gemika#4]
To speed up local development, many of us use "rbenv alias" to link patch level Ruby versions to existing ones.
Currently, Gemika does not support aliased Ruby versions and complaints about version missmatches:

Example travis.yml:
```yml

language: ruby
rvm:
  - 2.6.6
matrix:
  include:
    - gemfile: Gemfile.ruby266
      rvm: 2.6.6
```
In this case, running `matrix:install` with an aliased Ruby version does not work:
```
$ rbenv alias
> 2.6.6 => 2.6.5

$ rbenv shell 2.6.6
$ bundle exec rake matrix:install
> No gemfiles were compatible with Ruby 2.6.5
```

One way to work around this issue would be allowing Ruby versions without a patch level - e.g. `2.6.`.
